In [73]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [74]:
# How many negative numbers are there?

len(a[a < 0])

4

In [75]:
# How many positive numbers are there?

len(a[a > 0])

5

In [76]:
# How many even positive numbers are there?
count = 0
for i in a:
    if i > 0 and i % 2 == 0:
        count = count + 1
        
count

3

In [77]:
# If you were to add 3 to each data point, how many positive numbers would there be?

a_plus_3 = [a + 3]

In [78]:
a_pos = []
for i in a:
    if i > 0:
        a_pos.append(i)
a_pos
    

[4, 10, 12, 23, 3]

In [84]:
# If you squared each number, what would the new mean and standard deviation be?

a_sqr = np.array([a**2])

In [85]:
a_sqr.mean(), a_sqr.std()

(74.0, 144.0243035046516)

In [86]:
# A common statistical operation on a dataset is centering. This means to adjust the data 
#such that the mean of the data is 0. This is done by subtracting the mean from each data 
# point. Center the data set.

a_centered = np.array([a - a.mean()])
a_centered

array([[  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
        -10.]])

In [87]:
# Calculate the z-score for each data point. Recall that the z-score is given by: Z=(x−μ)/σ

a_zscore = np.array([(a-a.mean())/a.std()])
a_zscore

array([[ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
        -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
         0.        , -1.24034735]])

In [93]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

In [100]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
a = np.array(a)
sum_of_a = [a.sum()]
sum_of_a

[55]

In [102]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = a.min()
min_of_a

1

In [103]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = a.max()
max_of_a

10

In [105]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = a.mean()
mean_of_a

5.5

In [106]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = a.prod()
product_of_a

3628800

In [109]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = a**2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [115]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = a[a % 2 != 0]
odds_in_a

array([1, 3, 5, 7, 9])

In [116]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [127]:
# What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
# Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, 
# and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [140]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

b = np.array(b)
sum_of_b = b.sum()
sum_of_b

33

In [149]:
# Exercise 2 - refactor the following to use numpy. 
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

min_of_b = b.min()
min_of_b

3

In [150]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = b.max()
max_of_b

8

In [151]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = b.mean()
mean_of_b

5.5

In [155]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
#product_of_b = 1
#for row in b:
#    for number in row:
#        product_of_b *= number

product_of_b = b.prod()
product_of_b

20160

In [158]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
#squares_of_b = []
#for row in b:
#    for number in row:
#        squares_of_b.append(number**2)

squares_of_b = b**2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [161]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
#odds_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 != 0):
#            odds_in_b.append(number)

odds_in_b = b[b % 2 != 0]
odds_in_b

array([3, 5, 7])

In [162]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
#evens_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 == 0):
#            evens_in_b.append(number)

evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

In [163]:
# Exercise 9 - print out the shape of the array b.
print(b.shape)

(2, 3)


In [165]:
# Exercise 10 - transpose the array b.
print(b.transpose())

[[3 6]
 [4 7]
 [5 8]]


In [166]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

print(b.reshape(1, 6))

[[3 4 5 6 7 8]]


In [167]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

print(b.reshape(6, 1))

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [168]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array 
# prior to using numpy array methods.

In [169]:
# Exercise 1 - Find the min, max, sum, and product of c.

c = np.array(c)

In [171]:
c.sum(), c.min(), c.max(), c.prod()

(45, 1, 9, 362880)

In [172]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [173]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [176]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [178]:
# Exercise 5 - Transpose c and print out transposed result.
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [183]:
# Exercise 6 - Get the dot product of the array c with c.
c_prod = c*c
c_prod

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261



In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [ ]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d

In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

In [ ]:
# Exercise 4 - Find all the negative numbers in d

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.


In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [ ]:
# Exercise 8 - Print out the shape of d.

In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2